### ISSUE TITLE
`any` and `void` (or `undefined`) decoders

### ISSUE THREAD

**Issue by wms** [ai-labs-team/ts-utils#11]
I can't seem to find any built-in implementations for `and` or `void` types (`undefined` would be a suitable alternative to the latter.)

Am I missing something, is their omission by design, or should this be considered a feature request?

**Comment by nateabele** [comment]
Just using `Result.ok` works for the `any` case—which sort of points to a general primitive for custom decoding, i.e. (and I'm pseudo-coding here, check the docs & tests):

```typescript
object('Foo', {
  undefinedVal: ifElse(equals(undefined), Result.ok, Result.err)
});
```
